### ISSUE TITLE
В голосовалке не разрешать голосовать за свою фотку

### ISSUE THREAD

**Issue by mon-lolka** [vlle/Photoshnaya#12]
В голосовалке, когда голосующий юзер доходит до своей фотографии, как-то запрещать ему голосовать, например, 

дизейблить кнопку "🤍" и выводить сообщение: 

Нельзя голосовать за свою фотографию

**Comment by zyuhel** [comment]
а нужно ли ее вообще выводить в таком случае? может пусть у голосующего не будет его фотографии?

**Comment by detchenkov** [comment]
@vlle стоит наверно закрыть ишью раз оно пофикшено

**Comment by vlle** [comment]
Closed
